### ISSUE TITLE
Missing `test_transition.json` File and Clarification on Obtaining `robot_tensor`

### ISSUE THREAD

**Issue by 1301299126** [portal-cornell/interact#2]
I hope this message finds you well.

While developing a project using the interact-release repository, I encountered the following two issues and would greatly appreciate your assistance:

1. **Missing `test_transition.json` File**
2. **Unclear on how `robot_tensor = get_pose_history(json_data, "Robot")[::downsample_rate]` is obtained**

### 1. Missing `test_transition.json` File

According to the project documentation and code examples, I should find the `test_transition.json` file in the `interact/data/comad_hr/test_hr/` directory, but it seems to be missing. The specific issues are as follows:

- **File Content and Format**: What content should the `test_transition.json` file contain? What is its structure and data format?
- **Acquisition Method**: Should this file be created manually, or can it be downloaded from other project resources?

### 2. Clarification on `robot_tensor`

**Relevant Code Snippet:**
```python
alice_tensor = get_pose_history(json_data, "Kushal")[::downsample_rate, self.joint_used]
bob_tensor = get_pose_history(json_data, "Atiksh")[::downsample_rate, self.joint_used]
robot_tensor = get_pose_history(json_data, "Robot")[::downsample_rate]
```

- **Source of robot_tensor: In the dataset, what is the data structure corresponding to "Robot"? Are there any example data available for reference? Since there are only two characters in comad_hr, I am unclear about the origin of this data.**

**Comment by XinyunChi7** [comment]
Hi, I'm experiencing the same issue. Could you please let me know if there are any updates on it? Thanks.

**Comment by kushal2000** [comment]
@XinyunChi7 @1301299126 I just pushed a new commit that fixes both issues. The need for `transitions.json` is deprecated with the new CoMaD dataset.

FYI, there are some errors still in the dataset formatting for the Human-Robot data. I will push an updated commit this week. Can you let me know if you can run the code after this commit?

**Comment by XinyunChi7** [comment]
Hi @kushal2000, thanks for your reply :)
When I attempted to run 'pretrain_intent_forecaster.py' on the HH dataset, there appears to be an issue with the mapping JSON file used in the dataset loader: 
Available keys in mapping are: `dict_keys(['BackLeft', 'BackRight', 'BackTop', 'Chest', 'HeadFront', 'HeadSide', 'HeadTop', 'LElbowOut', 'LHandOut', 'LShoulderBack', 'LShoulderTop', 'LUArmHigh', 'LWristIn', 'LWristOut', 'RElbowOut', 'RHandOut', 'RShoulderBack', 'RShoulderTop', 'RUArmHigh', 'RWristIn', 'RWristOut', 'WaistLBack', 'WaistLFront', 'WaistRBack', 'WaistRFront'])`
While required joint names in ' synthetic_amass.py' are: `['Neck', 'L_Shoulder', 'R_Shoulder', 'L_Elbow', 'R_Elbow', 'L_Wrist', 'R_Wrist', 'L_Hand', 'R_Hand']`


And there's the error message I got: 
```
Error executing job with overrides: []
Traceback (most recent call last):
  File "scripts/pretrain_intent_forecaster.py", line 80, in main
    train_dataloader = get_dataloader(split='train', batch_size=cfg.Training.batch_size, include_amass=True, include_CMU_mocap=False)
  File "scripts/pretrain_intent_forecaster.py", line 37, in get_dataloader
    dataset_map['AMASS'][split] = Synthetic_AMASS(split=split)
  File "/home/username/interact/interact/utils/synthetic_amass.py", line 47, in __init__
    self.joint_used = np.array([mapping[joint_name] for joint_name in joint_names])
  File "/home/username/interact/interact/utils/synthetic_amass.py", line 47, in <listcomp>
    self.joint_used = np.array([mapping[joint_name] for joint_name in joint_names])
KeyError: 'Neck'
```
Could you please help me double-check the JSON file? Thanks!

**Comment by kushal2000** [comment]
Hi Xinyun, thanks for pointing out this issue. I realized that we never published the AMASS dataset preprocessing code. Please check the updated README.md for instructions to download AMASS dataset and train our models.

**Comment by XinyunChi7** [comment]
Thanks @kushal2000 for the updated instructions! 
After downloading AMASS datasets and trying to run preprocessing code, it works but there might be another issue - it seems the processeing code is used for MOCAP still (line 60: `frame_rate = pose_all['mocap_framerate']`), and some poses couldn't be loaded from some certian AMASS dataset files (e.g. might see messages like >`>> loading ACCAD, no poses at ACCAD_xxx.npz`).
Could you please double check the dataset preprocessing? Thank you.

**Comment by XinyunChi7** [comment]
> Thanks @kushal2000 for the updated instructions! After downloading AMASS datasets and trying to run preprocessing code, I noticed there might be another issue - it seems the processeing code is actually for MOCAP still (line 60: `frame_rate = pose_all['mocap_framerate']`), and seems couldn't load poses from AMASS (e.g. `>>> loading ACCAD` `no poses at ACCAD_xxx.npz` `...`). Could you please double check the dataset preprocessing? Thank you.

Hi I think it also works with AMASS dataset now :)

**Comment by kushal2000** [comment]
I believe this latest issue was resolved over e-mail. The problem was that you were loading the incorrect joints mapping file. The released code is working as is. I wanted to share this information for visibility to others.

**Comment by XinyunChi7** [comment]
Thanks @kushal2000! Yes I think the pretraining and finetuning on HH dataset works now.

**Comment by kushal2000** [comment]
Closing this thread as the latest commit has fixed all issues on this thread.
